#if !canImport(ObjectiveC)
import XCTest

extension SwiftSMTPVaporTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftSMTPVaporTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftSMTPVaporTests.__allTests__SwiftSMTPVaporTests),
    ]
}
#endif
